[package]
name = "cam-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "cam"
path = "src/main.rs"

[dependencies]
serde.workspace = true
cam-core = { path = "../cam-core" }
cam-storage = { path = "../cam-storage" }
cam-server = { path = "../cam-server" }
cam-service = { path = "../cam-service" }
serde_json.workspace = true

[dev-dependencies]
sha2.workspace = true

[lints]
workspace = true
