[package]
name = "cam-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
clipper2-rust.workspace = true
boostvoronoi.workspace = true
robust.workspace = true
serde.workspace = true
serde_json.workspace = true
roxmltree.workspace = true
svgtypes.workspace = true

[lints]
workspace = true
